workflows:
  version: 2.0
  build:
    name: Android Build Workflow
    max_build_duration: 120 # Minutes
    triggers:
      - github:
          push:
            branches:
              - main  # Trigger build on push to the main branch
    scripts:
      # Install dependencies for Flutter project
      - name: Install Flutter dependencies
        script: flutter pub get

      # Run unit tests to ensure everything is working correctly
      - name: Run Flutter tests
        script: flutter test

      # Build APK for Android release
      - name: Build APK (Release)
        script: flutter build apk --release

    # Define the artifacts you want to save after the build
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/flutter-apk/app-release.aab  # Android App Bundle for Play Store

    environment:
      vars:
        FLUTTER_CHANNEL: stable  # Use stable Flutter version
        ANDROID_HOME: $HOME/Android/Sdk  # Make sure Android SDK is available
